# Generated by Django 5.0.4 on 2024-04-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlistapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='rating',
        ),
    ]
