# Generated by Django 5.0.4 on 2024-04-27 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlistapp', '0002_remove_movie_rating_remove_tvshow_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='awardfor',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_awards', to='watchlistapp.person'),
        ),
    ]
